'use client';
import { useState, useEffect } from 'react';
import { useWriteContract, useWaitForTransactionReceipt, useAccount } from 'wagmi';
import { parseAbi } from 'viem';
import { ConnectKitButton } from 'connectkit';
import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  const { isConnected } = useAccount();
  
  // State management for English UI
  const [twitter, setTwitter] = useState('');
  const [discord, setDiscord] = useState('');
  const [bio, setBio] = useState('');
  const [generating, setGenerating] = useState(false);

  // Contract Address provided from Remix
  const CONTRACT_ADDRESS = '0xb9829f7661c8e3d088953eEa069c0b44FC20B484';

  // Transaction hooks
  const { data: hash, writeContract, isPending, error } = useWriteContract();
  const { isLoading: isConfirming, isSuccess } = useWaitForTransactionReceipt({ hash });

  // Status notifications (Toasts)
  useEffect(() => {
    if (isPending) toast.loading('Waiting for wallet approval...', { id: 'mint' });
    if (isConfirming) toast.loading('Transaction sent! Confirming on Neura...', { id: 'mint' });
    if (isSuccess) toast.success('SoulCard Minted Successfully! 🎉', { id: 'mint' });
    if (error) {
      const errorMessage = error.message.includes('User rejected') 
        ? 'Transaction rejected by user.' 
        : error.message.split('\n')[0];
      toast.error(`Error: ${errorMessage}`, { id: 'mint' });
    }
  }, [isPending, isConfirming, isSuccess, error]);

  // AI Bio Generator Logic
  const generateAIBio = async () => {
    if (!twitter) {
      toast.error('Please enter your Twitter handle first!');
      return;
    }
    
    setGenerating(true);
    try {
      const response = await fetch('/api/generate-bio', {
        method: 'POST',
        body: JSON.stringify({ twitter }),
      });
      const data = await response.json();
      if (data.bio) {
        setBio(data.bio);
        toast.success('Bio generated by AI!');
      }
    } catch (err) {
      toast.error('Failed to generate bio.');
    } finally {
      setGenerating(false);
    }
  };

  // Minting Function
  const handleMint = () => {
    if (!twitter || !discord) {
      toast.error('Please fill in Twitter and Discord handles!');
      return;
    }

    writeContract({
      address: CONTRACT_ADDRESS,
      abi: parseAbi(['function mintSoulCard(string twitter, string discord, string bio) public']),
      functionName: 'mintSoulCard',
      args: [twitter, discord, bio],
    });
  };

  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-6 bg-slate-50">
      <Toaster position="top-center" reverseOrder={false} />
      
      <div className="w-full max-w-md bg-white rounded-2xl shadow-xl p-8 space-y-6 border border-slate-100">
        <h1 className="text-3xl font-extrabold text-center text-slate-900 tracking-tight">
          Neura SoulCard
        </h1>
        
        <div className="flex justify-center pb-2">
          <ConnectKitButton />
        </div>

        {!isConnected ? (
          <p className="text-center text-slate-500 text-sm">
            Please connect your wallet to start minting.
          </p>
        ) : (
          <div className="space-y-4 pt-4 border-t border-slate-100">
            {/* Input Fields */}
            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase mb-1 ml-1">Twitter</label>
              <input 
                placeholder="@username" 
                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                onChange={(e) => setTwitter(e.target.value)}
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-500 uppercase mb-1 ml-1">Discord</label>
              <input 
                placeholder="username#0000" 
                className="w-full p-3 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-blue-500 outline-none transition-all"
                onChange={(e) => setDiscord(e.target.value)}
              />
            </div>
            
            {/* Bio Section with AI Trigger */}
            <div className="space-y-1">
              <div className="flex justify-between items-center px-1">
                <label className="text-xs font-bold text-slate-500 uppercase">Bio</label>
                <button 
                  onClick={generateAIBio}
                  disabled={generating}
                  className="text-[10px] bg-blue-50 text-blue-600 px-2 py-1 rounded-md font-black hover:bg-